### PR TITLE
Compressed Photos of Memories Section

### PR DESCRIPTION
**Pull request by anuragsai97**

### CODE REVIEW

**Comment by ghost** [comment]
You did not need to close this PR @anuragsai97 , You could just have added more commits to your branch and it'd have been updated automatically here :)

**Comment by anuragsai97** [comment]
This PR had unnecessary commits. So I closed it and created a new PR.

**Comment by FlameFractal** [comment]
@anuragsai97 
git rebase 
drop unnecesarry commits,
squash others
force push

**Comment by anuragsai97** [comment]
I didnot know about this. So I created a new PR. Will follow these from next time. Thank You.

**Comment by FlameFractal** [comment]
No problem :)
Learn new thing every time right ;)

Cheers,
V.

**Comment by ghost** [comment]
Is that signature `V` inspired from V for Vendetta ? @FlameFractal :laughing:

**Comment by FlameFractal** [comment]
Not really. Just my initial.

Cheers,
V.

**Pull request closed without merging**
